theme: jekyll-theme-cayman
title: Alessandro Sebastianelli
description: Ph.D. student at University of Sannio and ESA under OSIP contract
show_downloads: false
plugins:
  - jekyll-feed
  - jekyll-seo-tag
